# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-14 07:41
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', models.TextField(verbose_name=' 正文')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='文章状态')),
                ('abstract', models.CharField(blank=True, help_text='可选，如若为空将摘取正文的前54个字符', max_length=54, null=True, verbose_name='摘要')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='评论者名字')),
                ('user_email', models.EmailField(max_length=255, verbose_name='评论者邮箱')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论发表时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Article', verbose_name='评论所属文章')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='姓名')),
                ('QQ', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('duty', models.CharField(max_length=200, null=True, verbose_name='职务')),
                ('company_name', models.CharField(max_length=300, null=True, verbose_name='公司名称')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=200, null=True, verbose_name='职务')),
                ('duty_id', models.CharField(max_length=300, null=True, verbose_name='职位编号')),
                ('ship_age', models.CharField(max_length=100, null=True, verbose_name='船龄')),
                ('company_name', models.CharField(max_length=300, null=True, verbose_name='公司名称')),
                ('certificate_level', models.CharField(max_length=200, null=True, verbose_name='职务')),
                ('special_certificate', models.CharField(max_length=300, null=True, verbose_name='特殊证书')),
                ('route_area', models.CharField(max_length=300, null=True, verbose_name='路线区域')),
                ('recruitment_ship', models.CharField(max_length=300, null=True, verbose_name='招聘船型')),
                ('tonnage', models.CharField(max_length=200, null=True, verbose_name='吨位')),
                ('time', models.CharField(max_length=30, null=True, verbose_name='搜索时间')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=70, null=True)),
                ('duty_id', models.CharField(max_length=20, null=True, verbose_name='职务编号')),
                ('ship_age', models.CharField(max_length=10, null=True, verbose_name='船龄')),
                ('company_name', models.CharField(max_length=300, null=True, verbose_name='公司名称')),
                ('certificate_level', models.CharField(max_length=200, null=True, verbose_name='证书等级')),
                ('special_certificate', models.CharField(max_length=300, null=True, verbose_name='特殊证书')),
                ('route_area', models.CharField(max_length=300, null=True, verbose_name='路线区域')),
                ('recruitment_ship', models.CharField(max_length=300, null=True, verbose_name='招聘船型')),
                ('tonnage', models.CharField(max_length=200, null=True, verbose_name='吨位')),
                ('post_time', models.DateField(auto_now=True, max_length=300, null=True, verbose_name='搜索时间')),
                ('time', models.CharField(max_length=300, null=True, verbose_name='搜索时间')),
                ('onboard_location', models.CharField(max_length=300, null=True, verbose_name='上船地点')),
                ('onboard_time', models.CharField(max_length=200, null=True, verbose_name='上船时间')),
                ('salary', models.CharField(max_length=300, null=True, verbose_name='提供月薪')),
                ('contract', models.CharField(max_length=300, null=True, verbose_name='合同年限')),
                ('require', models.TextField(max_length=300, null=True, verbose_name='具体要求')),
                ('QQ', models.CharField(max_length=300, null=True, verbose_name='在线QQ')),
                ('contact', models.CharField(max_length=300, null=True, verbose_name='联系人')),
                ('tel', models.CharField(max_length=300, null=True, verbose_name='公司电话')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='公司地址')),
                ('property', models.CharField(max_length=200, null=True, verbose_name='公司性质')),
                ('email', models.CharField(max_length=300, null=True, verbose_name='电子邮箱')),
                ('introduction', models.TextField(max_length=300, null=True, verbose_name='公司介绍')),
            ],
            options={
                'ordering': ['-post_time'],
            },
        ),
        migrations.CreateModel(
            name='PersonalCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_name', models.CharField(max_length=200, null=True, verbose_name='称呼')),
                ('age', models.CharField(max_length=200, null=True, verbose_name='年龄')),
                ('gender', models.CharField(max_length=200, null=True, verbose_name='性别')),
                ('nation', models.CharField(max_length=200, null=True, verbose_name='民族')),
                ('tall', models.CharField(max_length=200, null=True, verbose_name='身高')),
                ('native', models.CharField(max_length=200, null=True, verbose_name='籍贯')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='现地址')),
                ('graduate', models.CharField(max_length=200, null=True, verbose_name='毕业院校')),
                ('graduate_time', models.CharField(max_length=200, null=True, verbose_name='毕业时间')),
                ('major', models.CharField(max_length=200, null=True, verbose_name='专业')),
                ('certificate_level', models.CharField(max_length=200, null=True, verbose_name='证书等级')),
                ('work_age', models.CharField(max_length=200, null=True, verbose_name='工作时间')),
                ('present_duty', models.CharField(max_length=200, null=True, verbose_name='现职位')),
                ('language', models.CharField(max_length=200, null=True, verbose_name='外语')),
                ('special_skills', models.CharField(max_length=2000, null=True, verbose_name='特殊技能')),
                ('duty', models.CharField(max_length=200, null=True, verbose_name='求职职位')),
                ('salary', models.CharField(max_length=200, null=True, verbose_name='月薪')),
                ('route_area', models.CharField(max_length=200, null=True, verbose_name='航线区域')),
                ('contract', models.CharField(max_length=200, null=True, verbose_name='合同年限')),
                ('recruitment_ship', models.CharField(max_length=200, null=True, verbose_name='招聘船型')),
                ('special_certificate', models.CharField(max_length=200, null=True, verbose_name='特殊证书')),
                ('post_time', models.DateField(auto_now_add=True, max_length=200, null=True, verbose_name='发布时间')),
                ('tel', models.CharField(max_length=200, null=True, verbose_name='电话')),
                ('QQ', models.CharField(max_length=200, null=True, verbose_name='QQ')),
                ('experience', models.TextField(max_length=200, null=True, verbose_name='工作经历')),
                ('introduction', models.TextField(max_length=200, null=True, verbose_name='自我介绍')),
                ('time', models.CharField(max_length=30, null=True, verbose_name='时间范围')),
            ],
            options={
                'ordering': ['-post_time'],
            },
        ),
    ]
