# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170814_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
    ]
